[package]
name = "parser"
version = "0.0.0"

edition.workspace = true

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
ast.workspace = true
common.workspace = true
def.workspace = true
